apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: "Detection-service"
  description: "Detector "
  annotations:
    argocd/app-name: Detection-service-dev
    backstage.io/kubernetes-id: Detection-service
    backstage.io/kubernetes-namespace: Detection-service-dev
    janus-idp.io/tekton-enabled : 'true'
    github.com/project-slug: OpenShiftCommons/Detection-service
    backstage.io/techdocs-ref: dir:.
  tags:
    - java
    - quarkus
  links:
    - url: https://devspaces.apps.cluster-dvzrb.dvzrb.sandbox1897.opentlc.com/#https://github.com/OpenShiftCommons/Detection-service?che-editor=che-incubator/che-code/insiders&devfilePath=.devfile-vscode.yaml
      title: OpenShift Dev Spaces (VS Code)
      icon: web
    - url: https://devspaces.apps.cluster-dvzrb.dvzrb.sandbox1897.opentlc.com/#https://github.com/OpenShiftCommons/Detection-service?che-editor=che-incubator/che-idea/latest&devfilePath=.devfile-intellij.yaml
      title: OpenShift Dev Spaces (JetBrains IntelliJ)
      icon: web
spec:
  type: service
  lifecycle: production
  owner: "group:default/research-team"
  providesApis:
    - "Detection-service"
---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: "Detection-service"
  description: "Detector "
spec:
  type: openapi
  lifecycle: production
  owner: "group:default/research-team"
  definition:
    $text: ./openapi.yaml
